#!/usr/bin/env nu

# Regenerate app/src/main/assets/emoji.txt from Unicode's emoji-test.txt.
#
# Keeps fully-qualified emoji with their groups, in Unicode's order. Drops
# the Component group and every skin-tone variant; the panel shows base
# emoji only. The output is committed, so this only runs on an Emoji
# version bump.
def main [
    source: string = "https://unicode.org/Public/emoji/latest/emoji-test.txt" # URL or local path
] {
    let text = if ($source | str starts-with "http") { http get --raw $source } else { open --raw $source }
    let lines = $text | lines
    let version = $lines | where ($it | str starts-with "# Version:") | first | str replace "# Version: " ""

    mut groups = []
    mut group = ""
    mut emoji = []
    for line in $lines {
        if ($line | str starts-with "# group: ") {
            if ($emoji | is-not-empty) { $groups = $groups | append $"($group)\t($emoji | str join ' ')" }
            $group = $line | str replace "# group: " ""
            $emoji = []
        } else if ($group != "Component") and ($line =~ '; fully-qualified') and not ($line =~ '\b1F3F[B-F]\b') {
            $emoji = $emoji | append ($line | parse --regex '# (?<e>\S+) E' | get e.0)
        }
    }
    if ($emoji | is-not-empty) { $groups = $groups | append $"($group)\t($emoji | str join ' ')" }

    let out = $env.FILE_PWD | path join .. app src main assets emoji.txt
    [$"# Generated by scripts/emoji.nu from emoji-test.txt, Emoji ($version)." ...$groups]
        | str join "\n"
        | $in + "\n"
        | save --force $out
    print $"wrote ($groups | length) groups to ($out)"
}
